/* Listado de colegios */
const COLEGIOS = [
  "Centro Cultural Haedo",
  "Centro Educativo Arquidiocesano Espíritu Santo",
  "Centro de Educación Integral San Ignacio",
  "Colegio Alemán de Lanús",
  "Colegio Almafuerte - Bernal",
  "Colegio Argentino Almirante Brown - Pilar",
  "Colegio Asunción de María",
  "Colegio Bertrand Russell",
  "Colegio Buenos Aires",
  "Colegio Canadá",
  "Colegio Cardenal Copello",
  "Colegio Cristiano de Martínez",
  "Colegio De las Victorias",
  "Colegio Divina Pastora",
  "Colegio Durham",
  "Colegio Esclavas del Sagrado Corazón de Jesús",
  "Colegio Evangélico Alfredo Furniss",
  "Colegio F.A.S.T.A Niño Jesús",
  "Colegio Francesco Faa Di Bruno",
  "Colegio French - Banfield",
  "Colegio Fundación Cristiana",
  "Colegio Grilli - Canning",
  "Colegio Grilli - Monte Grande",
  "Colegio Inglés Horacio Watson",
  "Colegio Jesús María",
  "Colegio José Hernández - Villa Ballester",
  "Colegio Lucero del Norte",
  "Colegio Mariano Moreno",
  "Colegio Martín y Omar",
  "Colegio Monseñor Dillon",
  "Colegio Nazareth",
  "Colegio Newlands",
  "Colegio Niño Jesús de Praga",
  "Colegio North Hills",
  "Colegio Ntra. Sra. De Luján - Adrogué",
  "Colegio Ntra. Sra. de la Misericordia - Rosario",
  "Colegio Nueva Generación",
  "Colegio Nuevo Pensar",
  "Colegio Parroquial Nuestra Señora del Refugio",
  "Colegio Paula Montal",
  "Colegio Privado IMEI S.R.L",
  "Colegio Ramos Mejía",
  "Colegio Sagrado Corazón de Jesús",
  "Colegio San Cayetano - Villa Adelina",
  "Colegio San José - Marcos Paz",
  "Colegio San José de la Palabra de Dios",
  "Colegio San Ladislao",
  "Colegio San Martín de Tours",
  "Colegio San Martín de Tours - San Fernando",
  "Colegio San Maximiliano Kolbe",
  "Colegio San Miguel",
  "Colegio San Pablo - Salta",
  "Colegio San Pablo Apóstol",
  "Colegio San Pablo Norte",
  "Colegio San Patricio - Moreno",
  "Colegio San Patricio - Rosario, Santa Fe",
  "Colegio San Ramón",
  "Colegio Santa Ana",
  "Colegio Santa Brígida",
  "Colegio Santa Teresa - Tigre",
  "Colegio Santa Trinidad",
  "Colegio Santo Tomás",
  "Colegio Secundario Santa María",
  "Colegio St. Hildas",
  "Colegio Stanford de Buenos Aires",
  "Colegio de Enseñanza Secundaria Básica San Diego",
  "Colegio de Nuestra Señora",
  "Colegio del Norte",
  "Complejo Educativo Pbro E. E. Natta",
  "Comunidad Educativa Weitzman",
  "EESOPI N° 3083 \"Dante Alighieri\"",
  "EPM Computación",
  "Escuela Argentina",
  "Escuela Argentina General Belgrano",
  "Escuela Cangallo",
  "Escuela Cristiana Vida",
  "Escuela Cristiana de la Puerta Abierta",
  "Escuela E.E.M.P.I. Nº 8062 \"San Francisco de Asís\" - Sastre",
  "Escuela Italo-Argentina San Mauro",
  "Escuela Jean Piaget",
  "Escuela Modelo Mariano Acosta",
  "Escuela Modelo Sarmiento",
  "Escuela Modelo de Bella Vista",
  "Escuela Nº 8120 \"Nuestra Señora de Las Mercedes\"",
  "Escuela República Argentina",
  "Escuela Secundaria Antonio Toro",
  "Escuela Secundaria Tato",
  "Escuela de Educación Integral Sarmiento",
  "Escuela de Educación Media Instituto Modelo Almafuerte - Merlo",
  "Escuela de Educación Secundaria Orientada Particular Autorizada Nº 3079 – ICES",
  "Escuela de Educación Secundaria Técnica Henry Ford",
  "Escuela de la Costa",
  "Instituto Adolfo Alsina",
  "Instituto Almafuerte - Esteban Echeverria",
  "Instituto Almirante Guillermo Brown",
  "Instituto Asociación Educativa Pío León",
  "Instituto Bilingüe Sagrada Familia",
  "Instituto Buckingham Quilmes - Escuela Secundaria Los Cedros",
  "Instituto Calasancio Divina Pastora",
  "Instituto Canbazyan",
  "Instituto Cardenal Stepinac",
  "Instituto Cardoso",
  "Instituto Carlos Steeb",
  "Instituto Ceferino Namuncurá - CABA",
  "Instituto Ceferino Namuncurá - Florida",
  "Instituto Compañía de María",
  "Instituto D-243 “Prof. José María Ruperto Gelos”",
  "Instituto Del Sur",
  "Instituto Divino Corazón",
  "Instituto Don Orione",
  "Instituto ESBA Flores",
  "Instituto ESBA Lugano",
  "Instituto Eduardo L. Holmberg",
  "Instituto Educacional Dr. Luis Federico Leloir",
  "Instituto Educacional San Miguel – San Miguel",
  "Instituto Evangélico Americano - Villa del Parque",
  "Instituto Gabriele D’annunzio",
  "Instituto General José de San Martín",
  "Instituto General Pacheco",
  "Instituto González Pecotche",
  "Instituto Griego Atenágoras I",
  "Instituto Guadalupe",
  "Instituto Hölters",
  "Instituto Inmaculada Concepción de Nuestra Señora de Lourdes",
  "Instituto Jesús Sacramentado",
  "Instituto La Primera Enseñanza",
  "Instituto Lausanne",
  "Instituto Luigi Pirandello",
  "Instituto Madre de los Emigrantes",
  "Instituto Madre del Divino Pastor",
  "Instituto Mallinckrodt",
  "Instituto Manuel Belgrano",
  "Instituto Manuel Belgrano - Berazategui",
  "Instituto Manuel Belgrano - Quilmes High School",
  "Instituto Mario Madeddu",
  "Instituto María Auxiliadora",
  "Instituto María Reina",
  "Instituto Mater Ter Admirabilis",
  "Instituto Miguel Cané",
  "Instituto Nuestra Señora de Fátima - Cipolletti",
  "Instituto Nuestra Señora de Fátima - Del Viso",
  "Instituto Nuestra Señora de Luján - Villa Ballester",
  "Instituto Nuestra Señora de la Merced - Arroyito, Córdoba",
  "Instituto Nuestra Señora de la Merced - San Andrés",
  "Instituto Nuestra Señora de la Misericordia - Mataderos",
  "Instituto Nuestra Señora del Carmen",
  "Instituto Nuestra Señora del Pilar",
  "Instituto Primo Capraro",
  "Instituto Privado Claret",
  "Instituto Privado Enrique Guillermo Hood SRL",
  "Instituto Privado Esclavas del Sagrado Corazón de Jesús",
  "Instituto Privado Francisco de Asís - Mariano Acosta",
  "Instituto Privado de la Paz",
  "Instituto Ranelagh",
  "Instituto Roberto Arlt",
  "Instituto Saint Charles College",
  "Instituto San Alfonso",
  "Instituto San Antonio de Padua",
  "Instituto San Carlos",
  "Instituto San Eduardo",
  "Instituto San Gregorio",
  "Instituto San José - Morón",
  "Instituto San José - Quilmes",
  "Instituto San Luis",
  "Instituto San Marcos",
  "Instituto San Martín de Los Andes",
  "Instituto San Martín de Tours",
  "Instituto San Román",
  "Instituto Santa Ana y San Joaquín",
  "Instituto Santa Catalina Virgen y Mártir",
  "Instituto Santa Clara de Asís",
  "Instituto Santa Inés",
  "Instituto Santa Maria del Rosario",
  "Instituto Santa María de Guadalupe",
  "Instituto Santa Rita",
  "Instituto Santa Teresa de Jesús",
  "Instituto Santa Teresita del Niño Jesús",
  "Instituto Santo Domingo",
  "Instituto Santísima Virgen Niña",
  "Instituto Sara Chamberlain de Eccleston",
  "Instituto Secundario Gral Belgrano",
  "Instituto Secundario Lincoln",
  "Instituto Summa",
  "Instituto Susini",
  "Instituto Técnico Dr. Emilio Lamarca",
  "Instituto Técnico Industrial San Judas Tadeo",
  "Instituto Técnico María Reina",
  "Instituto Valle Grande",
  "Instituto Ángel D’ Elía",
  "Moderno Instituto Secundario",
  "New Model International School",
  "Programa EduTech",
  "Programa Inclusión Digital",
  "St. Paul's College - Hurlingham",
  "Washington School",
];



// Formateo texto: minúsculas, sin tildes, sin espacios de más.
function normalizar(s){
  return (s || '')
    .toLowerCase()
    .normalize('NFD').replace(/[\u0300-\u036f]/g, '') // saca tildes
    .replace(/\s+/g, ' ')                             // elimina espacios extra
    .trim();
}

// Devuelve el nombre EXACTO del registro si el texto coincide con alguno; si no, null.
function resolverColegio(valor){
  const n = normalizar(valor);
  return COLEGIOS.find(c => normalizar(c) === n) || null;
}
